---
resources:
  - name: spike-concurse-cf-deploy
    type: git
    source:
      uri: https://github.com/keymon/spike-concurse-cf-deploy
      branch: master

  - name: tfstate-s3
    type: s3
    source:
      bucket: hectorc-tfstate
      versioned_file: terraform.tfstate
      region_name: eu-west-1
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}

jobs:

  - name: init-tfstate-s3
    plan:
      - get: spike-concurse-cf-deploy
        path: code
      - task: apply-tfstate-s3
        config:
          platform: linux
          image: docker:///keymon/terraform
          inputs:
            - name: spike-concurse-cf-deploy
          run:
            path: sh
            args:
            - -c
            - |
              cd spike-concurse-cf-deploy/bosh/aws
              terraform apply -var env={{deploy_env}} -target=aws_s3_bucket.terraform_state
        on_success:
          put: tfstate-s3
          params:
            from: ./tfstate-s3/terraform.tfstate


