---
resources:
  - name: spike-concurse-cf-deploy
    type: git
    source:
      uri: https://github.com/keymon/spike-concurse-cf-deploy
      branch: master

  - name: tfstate-s3
    type: s3
    source:
      bucket: {{bucket_name}}
      versioned_file: terraform.tfstate
      region_name: eu-west-1
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}

  - name: id_rsa-s3
    type: s3
    source:
      bucket: {{bucket_name}}
      versioned_file: id_rsa.tgz
      region_name: eu-west-1
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}

jobs:

  - name: init-tfstate-s3
    plan:
      - get: spike-concurse-cf-deploy
        path: code
      - try:
          task: apply-tfstate-s3
          config:
            platform: linux
            image: docker:///keymon/terraform
            inputs:
              - name: spike-concurse-cf-deploy
            run:
              path: sh
              args:
              - -c
              - |
                export AWS_ACCESS_KEY_ID={{aws_access_key_id}}
                export AWS_SECRET_ACCESS_KEY={{aws_secret_access_key}}
                export TF_VAR_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
                export TF_VAR_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
                cd spike-concurse-cf-deploy/bosh/aws
                terraform apply -var env={{deploy_env}} -target=aws_s3_bucket.terraform_state
          on_success:
            put: tfstate-s3
            params:
              from: ./spike-concurse-cf-deploy/bosh/aws/terraform\.tfstate$
      # Just do one get once to check that the object is there
      - get: tfstate-s3
      # Generate SSH key
      - try:
          get: id_rsa-s3
          on_failure:
            task: ssh-keygen
            config:
              platform: linux
              image: docker:///ubuntu
              outputs:
                - name: id_rsa-s3
              run:
                path: sh
                args:
                - -c
                - |
                  set -e
                  apt-get install openssh-client -y
                  ssh-keygen -f id_rsa  -N '' && \
                  tar -cvzf id_rsa-s3/id_rsa.tgz id_rsa id_rsa.pub
      - put: id_rsa-s3
        params:
          from: ./id_rsa-s3/id_rsa.tgz

